### ISSUE TITLE
SDXL support for style and refiner parameters

### ISSUE THREAD

**Issue by ramsrigouthamg** [segmind/segmind-py#5]
Hi team,

Currently, SDXL API doesn't support style and refiner parameters to be passed in.
Can you please add support for the same?

Thanks!

**Comment by rohitrameshrao** [comment]
@sumanthdonapati can you check if this can be added quickly?

**Comment by sumanthdonapati** [comment]
Hi, it seems to be working. can you please try it again?
sample json:
{
    "prompt": "cyborg style, 1girl, solo, black hair, blue eyes, cable, mechanical parts, spine, android, cyborg, science fiction, simple background, black background from behind, high quality, high resolution",
    "negative_prompt":"drawing, painting, illustration, rendered, low quality, low resolution",
    "samples": 1,
    "scheduler": "UniPC",
    "num_inference_steps": 30,
    "guidance_scale": 7,
    "img_height": 1024,
    "img_width": 1024,
    "seed": 3968197770,
    "high_noise_fraction":0.2,
    "style":"anime"
}

**Comment by ramsrigouthamg** [comment]
@sumanthdonapati 
The generate function here doesn't support style or refiner params. I just tried again
https://github.com/segmind/segmind-py/blob/main/segmind/SDXL.py

**Comment by sumanthdonapati** [comment]
Yeah, I will send a PR with updated code for this

**Comment by sumanthdonapati** [comment]
Sent a PR to support refiner and style params. @rohitrameshrao can you approve it?
example:
from segmind import SDXL
model = SDXL('SG_86e6cb215e8b257d')
img = model.generate('apple tree',style="anime",high_noise_fraction=0.8)

**Comment by ramsrigouthamg** [comment]
Fixed!
